### ISSUE TITLE
issue: different versions of packages

### ISSUE THREAD

**Issue by rokamu623** [azu-lab/RD-Gen#1]
In setup.sh, it sometimes appears that `setup.sh completed correctly` even though the incorrect package version was installed.

The problem caused by this becomes apparent only when generator run.
I solved the problem by `pip3 install --upgrade` the package that was causing the error on run.

Besides the fundamental solution, I think this should be mentioned as a precaution on `README`.

**Comment by atsushi421** [comment]
I have specified a version and close it.
