### ISSUE TITLE
suggestion: console output of progress

### ISSUE THREAD

**Issue by rokamu623** [azu-lab/RD-Gen#2]
When the number of DAGs and parameter combinations is large, the tool's execution time is prolonged, and the process seems to stop in an infinite loop or something.

It would be helpful to have an indication such as `n DAGs generated` on the console.

**Comment by atsushi421** [comment]
@rokamu623 
Thank you very much for your thoughtful suggestion.
Can you paste the config file when an infinite loop occurs?

**Comment by rokamu623** [comment]
@atsushi421 
My actual proposal is as follows:
The execution time is very long, but there is no change in the console display, and I want to see the progress.

No actual infinite loop has occurred.
Sorry for the misleading expression.

**Comment by atsushi421** [comment]
Progress is now output and closed.
