### ISSUE TITLE
bug: incorrect output for single entry node

### ISSUE THREAD

**Issue by rokamu623** [azu-lab/RD-Gen#4]
A DAG with multiple entry nodes was generated, even though the entry nodes was fixed to 1 in the config file.

DAG generation was performed with the following parameters:
```
Seed: 126
Number of DAGs: 30

Graph structure:
  Generation method: G(n, p)
  Number of nodes:
    Random: (5, 15, 1)
  Probability of edge:
    Random: (0.3, 0.9, 0.1)
  Number of entry nodes:
    Fixed: 1
  Number of exit nodes:
    Fixed: 1
  Ensure weakly connected: True

Properties:
  Execution time:
    Random: (2, 15, 1)
  End-to-end deadline:
    Ratio of deadline to critical path:
      Random: (1.0, 1.5, 0.1)

Output formats:
  Naming of combination directory: "Abbreviation"
  DAG:
    YAML: True
    JSON: False
    XML: False
    DOT: False
  Figure:
    Draw legend: False
    PNG: True
    SVG: False
    EPS: False
    PDF: False
```

**Comment by rokamu623** [comment]
The config file used and the DAG generated are as follows:
config:
https://drive.google.com/file/d/1cAd-EaWEtVEBAMY63eX9SUMQ6MQb3ASg/view?usp=sharing

DAG(png):
https://drive.google.com/file/d/1JJ0vaE-1gA8dkJFY4QHKehuj-HsGfkaX/view?usp=sharing

**Comment by atsushi421** [comment]
@rokamu623 
I have fixed the bug, could you please check?
